export const cartData = {
  home: 'Home',
  cart: 'Cart',
  arrow: '/icons/arrow.svg',
  title: 'Your Cart',
  cross: '/icons/Vector 7.svg',
  fatca: '/images/FATCA.svg',
  ship: '/images/Rectangle 505.svg',
  scs: 'SCS – SANCTIONS COMPLIANCE SPECIALIST',
  value: '$499.00',
  subText: '1 Year membership',
  total: 'SUBTOTAL',
  agree: 'I agree ',
  privacy: 'Privacy Policy.',
  check: 'Checkout',
  back: 'Back to Home',
  certificate: 'View Certifications',
  payment: 'Payment Details ',
  purchase: 'Complete your purchase by providing your payment details.',
  cardDet: 'Card details',
  mm: 'MM/YY',
  email: 'Email',
  address: 'Billing address ',
  holder: 'Cardholder name',
  discount: 'Discount code',
  totals: 'total',
  pay: 'Pay $1099',
  secured: 'Payments are secure and encrypted',
  checkout: 'Checkout',
};
