export const modalData = {
  text: 'Schedule Exam',
  date: 'Date',
  confirm: 'Confirm',
  syllabus: 'Syllabus',
  slides: 'Slides',
  text2: 'Language',
  languages: [
    {
      id: '1',
      name: 'English',
    },
    {
      id: '2',
      name: 'Spanish',
    },
    {
      id: '1',
      name: 'Arabic',
    },
    {
      id: '1',
      name: 'French',
    },
  ],
  eidt: 'Edit Info',
  editImg: '/images/edit.svg',
  export: '/images/export.svg',
  profileText: 'Update image',
  name: 'Full Name',
  company: 'Company Name',
  ctx: 'Apply',
  contactEdit: 'Edit Contact',
  phone: 'Phone',
  location: 'Location',
  email: 'Email',
  time: 'Time',
  promo: 'Promo Code',
  title: 'Title',
  reciverEmail: 'Receiver Email',
};
