export const cardData = {
  info: 'Personal information',
  name: 'Jacob Lewis',
  company: 'Deloitte Company',
  profileImg: '/images/Rectangle 449.webp',
  edit: '/icons/Group 29.svg',
  contact: 'Contact',
  phone: '+1 (505) 555-1234',
  location: 'United State, Denver ',
  email: 'jsmith@yourdomain.com',
  time: 'GMT-7',
  phoneIcon: '/icons/phone-call 1.svg',
  mailIcon: '/icons/mail 1.svg',
  locationIcon: '/icons/location 1.svg',
  timerIcon: '/icons/timer 1.svg',
  member: 'Membership',
  subTitle: 'Joined',
  dateJoined: '01/11/2019',
  expire: 'Expires',
  expireDate: '01/11/2020',
  arrow: '/icons/Arrow 4.svg',
  cardIcon: '/icons/fatca.svg',
  title: 'SCS – SANCTIONS COMPLIANCE SPECIALIST',
  subText:
    'New and practical information about Sanctions Compliance, globally.',
  cart: 'Add to cart',
  forword: '/icons/forward.svg',
  share: '/icons/share 1.svg',
  download: '/icons/pdf download.svg',
  forwordText: 'Send',
  shareText: 'Share',
  downloadText: 'Download PDF',
  purchaseImg: '/images/purchase.webp',
  purchaseDate: '19 February 2023',
  purchaseTitle:
    'How should we manage our sanctions program and the updates of this space?',
  hour: '1 Hour',
  subHour: 'Duration',
  virtual: 'Virtual',
  delivery: 'Delivery Channel',
  webinar: 'Webinar',
  event: 'Event Type',
  value: '$99.00',
  ctx: 'More Information',
  result: 'EXAM RESULTS',
  congrats: 'Congratulations! You passed the exam.',
  btnText: 'Certificate',
  fail: 'Unfortunately the exam failed.',
  report: 'Coaching Report',
  schedule: 'Show Schedule',
  btnPract: 'Proctoring System',
  renew: 'Renew Membersip',
  complete: '/images/Group 1656.svg',
  comp: 'complete',
  inprogress: 'Inprogress',
  already: 'Already bought',
  purchaseYet: 'did not purchased yet',
};
